import fs from 'node:fs';
import path from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { root, twin } from './evidence/semantic.mjs';
import { read } from './evidence/hash.mjs';
const recipes=[['digital-twin.schema.json','contracts.d.ts','CanonicalTwinContract'],['m1-inventory.schema.json','inventory.d.ts','M1InventoryContract']];
for(const [input,filename,name]of recipes){
 const source=read(path.join(twin,'schemas',input));
 const text=await compile({...source,$id:undefined,oneOf:Object.keys(source.$defs).map(k=>({$ref:'#/$defs/'+k}))},name,{bannerComment:`/* Generated from digital-twin/schemas/${input}.\n * Read-only contract source: regenerate with pnpm --dir digital-twin types.\n * Do not edit this file. */`,unreachableDefinitions:true,style:{singleQuote:true,semi:true},cwd:path.join(twin,'schemas'),maxItems:6});
 const output=path.join(root,'picarx-companion/src/generated/twin',filename);
 if(process.argv.includes('--check')){if(!fs.existsSync(output)||fs.readFileSync(output,'utf8')!==text)throw Error('GENERATED_TYPES_DRIFT: '+filename);console.log('Generated types match '+input);}
 else{fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,text);console.log('Generated '+filename);}
}
