fn main() {
    #[cfg(not(feature = "m3-native-test"))]
    for name in ["m3_test_fresh", "m3_test_fault"] {
        let path = format!("permissions/autogenerated/{name}.toml");
        if std::path::Path::new(&path).exists() {
            std::fs::remove_file(path).expect("remove test-only generated permissions");
        }
    }
    #[cfg(feature = "m3-native-test")]
    const COMMANDS: &[&str] = &[
        "studio_power_state",
        "studio_escape_capture",
        "load_companion_state",
        "list_companion_aggregates",
        "list_progress_imports",
        "commit_session_command",
        "export_session",
        "import_session",
        "recover_session",
        "quarantine_legacy_raw",
        "studio_copy_photo", "studio_read_photo", "studio_export_evidence",
        "m3_test_fresh",
        "m3_test_fault",
    ];
    #[cfg(all(feature = "m3-persistence", not(feature = "m3-native-test")))]
    const COMMANDS: &[&str] = &[
        "studio_power_state",
        "studio_escape_capture",
        "load_companion_state",
        "list_companion_aggregates",
        "list_progress_imports",
        "commit_session_command",
        "export_session",
        "import_session",
        "recover_session",
        "quarantine_legacy_raw",
        "studio_copy_photo", "studio_read_photo", "studio_export_evidence",
    ];
    #[cfg(feature = "m3-persistence")]
    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new()
            .commands(COMMANDS)
            .permissions_path_pattern("permissions/normal/*.toml"),
    );
    #[cfg(not(feature = "m3-persistence"))]
    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&["studio_power_state"]).permissions_path_pattern("permissions/normal/*.toml"),
    );
    tauri_build::try_build(attributes).expect("Tauri build configuration");
}
