import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {base,validateParameters,validateReceipt,engineeringInput,pair,mustNotDrive} from '../../../tools/evidence/m5-instructional.mjs';
import {receiptFor} from '../../../tools/evidence/m5-instructional-receipts.mjs';
import {loadRegistry,validateRegistry,validateShape,twin} from '../../../tools/evidence/semantic.mjs';
import {read} from '../../../tools/evidence/hash.mjs';
const input=read(path.join(base,'instructional-parameters.json')),reg=loadRegistry(),steps=read(path.join(twin,'components/inventory/planning-steps.json')).steps;
const validate=p=>validateParameters(p,{sourceBytes:false});
const find=(p,suffix)=>p.definitions.find(d=>d.definitionId==='PX-V40-DEF-'+suffix);
const mutate=(name,edit,reason)=>test('negative: '+name,()=>{const p=structuredClone(input);edit(p);assert.throws(()=>validate(p),reason);});
mutate('proxy cannot become engineering admitted',p=>p.definitions[0].engineeringStatus='ENGINEERING_ADMITTED',/STRICT_STATUS_PROMOTION/);
test('negative: visual estimate cannot become VERIFIED Measurement',()=>{const r=structuredClone(reg),m=r.measurements.find(m=>m.value.state==='unresolved'&&m.subjectId==='PX-V40-DEF-CAMERA');m.value={state:'known',value:25,unit:'mm',confidence:'VERIFIED',evidenceRefs:['PX-EV-PHOTO-03'],uncertainty:{state:'bounded',minus:0,plus:0}};assert.throws(()=>validateRegistry(r,{steps,artifacts:false}),/SOURCE_SCOPE_PROMOTION/);});
test('negative: DERIVED without reproducible derivation',()=>assert.throws(()=>validateShape('NumericValue',{state:'known',unit:'mm',value:25,confidence:'DERIVED',evidenceRefs:['PX-EV-PHOTO-03'],uncertainty:{state:'bounded',minus:1,plus:1}}),/derivationRef/));
for(const [name,id] of [['SG90','SERVO-PAN'],['generic TT','MOTOR-LEFT'],['HC-SR04','ULTRASONIC']])mutate(name+' identity promotion',p=>find(p,id).exactOEMIdentity=name,/exactOEMIdentity/);
mutate('camera conflicting values cannot be averaged',p=>{for(const a of find(p,'CAMERA').instructionalApproximations)if(a.name==='length')a.value=24.5;},/CAMERA_NO_AVERAGING/);
mutate('ultrasonic voltage conflict cannot disappear',p=>find(p,'ULTRASONIC').protectedFacts.openConflicts.find(c=>c.id.includes('ULTRASONIC')).status='resolved',/PROTECTED_TUTORIAL_FACT_MUTATION/);
mutate('Washer A cannot collapse into Washer B',p=>{const a=p.definitions.find(d=>d.definitionId.includes('WASHER-A')),b=p.definitions.find(d=>d.definitionId.includes('WASHER-B'));a.protectedFacts=b.protectedFacts;},/PROTECTED_TUTORIAL_FACT_MUTATION/);
mutate('Washer A and B visual forms cannot collapse',p=>{find(p,'WASHER-A').instructionalApproximations=structuredClone(find(p,'WASHER-B').instructionalApproximations);},/WASHER_APPEARANCE_COLLAPSE/);
mutate('printed screw nominal length cannot change in presentation',p=>p.definitions.find(d=>d.recipe==='screw'&&d.protectedFacts.definition.name.startsWith('M3x25')).instructionalApproximations.find(a=>a.name==='length').value=6,/PRINTED_LENGTH_SUBSTITUTION/);
mutate('front wheel cannot become rear wheel',p=>find(p,'WHEEL-FRONT').instructionalApproximations.find(a=>a.name==='spokeCount').value=5,/WHEEL_ROLE_SUBSTITUTION/);
mutate('left motor cannot become right motor',p=>find(p,'MOTOR-LEFT').semanticRole='right',/MOTOR_ROLE_SUBSTITUTION/);
mutate('integral lead cannot become extra stock',p=>p.integralLeads[0].purchasedItemIncrement=1);
mutate('rivet pin cannot become extra purchased element',p=>p.definitions.find(d=>d.recipe==='rivet').protectedFacts.ownedElements[1].inventoryCountedSeparately=true,/PROTECTED_TUTORIAL_FACT_MUTATION/);
test('negative: approximate route cannot become engineering input',()=>assert.throws(()=>engineeringInput({track:'instructional-only',metricRoute:[[0,0,0],[1,1,1]]},'engineeringRoute'),/FIREWALL/));
test('negative: Pi5 guidance cannot become manufacturing input',()=>assert.throws(()=>engineeringInput(find(input,'PI5'),'manufacturing'),/FIREWALL/));
test('negative: relabeling a proxy as engineering still requires strict proof',()=>assert.throws(()=>engineeringInput({track:'engineering',definitionId:'PX-V40-DEF-PI5'},'engineeringSolver'),/STRICT_ENGINEERING_PROOF_REQUIRED/));
test('negative: private photo cannot become runtime/public artifact',()=>{const d=input.definitions[0],shape={definitionId:d.definitionId,status:'PASS',solidCount:d.expectedRigidSolids,engineeringAdmission:false},r=receiptFor(d,shape,['x.svg']);r.artifactPaths=['picarx-companion/public/content/owner.jpg'];assert.throws(()=>validateReceipt(r,input,shape),/PRIVATE_OR_RUNTIME_ARTIFACT_ROOT/);});
for(const purpose of mustNotDrive)test('negative: presentation blocked for '+purpose,()=>assert.throws(()=>engineeringInput(input.definitions[0],purpose),/FIREWALL/));
mutate('source limitations cannot be discarded',p=>p.definitions[0].sourceLimitations=['Unrelated replacement text'],/SOURCE_LIMITATION_DROPPED/);
mutate('canonical unknown cannot gain numeric payload',p=>p.definitions[0].canonicalUnknowns[0].value.value=5,/CANONICAL_UNKNOWN_MUTATION/);
mutate('fifty scope cannot duplicate one definition',p=>p.definitions[1]=p.definitions[0],/EXACT_FIFTY_DEFINITION_CLOSURE/);
test('positive: strict blocked and instructional admitted coexist',()=>assert.deepEqual(pair(false,true),{engineeringStatus:'BLOCKED',instructionalStatus:'INSTRUCTIONAL_ADMITTED'}));
test('positive: independent engineering pass and instructional pass coexist (synthetic policy unit)',()=>assert.deepEqual(pair(true,true),{engineeringStatus:'ENGINEERING_ADMITTED',instructionalStatus:'INSTRUCTIONAL_ADMITTED'}));
test('positive: engineering blockers retained',()=>{validate(input);assert(input.definitions.every(d=>d.blockerIds.length));});
test('positive: canonical unknowns remain unresolved',()=>assert(input.definitions.every(d=>d.canonicalUnknowns.every(u=>u.value.state==='unresolved'))));
test('positive: presentation records contain no engineering Measurements',()=>assert(input.definitions.every(d=>d.instructionalApproximations.every(a=>a.nonEngineering===true))));
test('positive: replaceable visual dimensions preserve component identities',()=>{const p=structuredClone(input);const d=find(p,'BATTERY');d.instructionalApproximations.find(a=>a.name==='length').value+=1;validate(p);assert.deepEqual(p.definitions.map(d=>d.definitionId),input.definitions.map(d=>d.definitionId));});
test('positive: provenance closure and source limits',()=>assert(input.definitions.every(d=>d.sourceRefs.length&&d.sourceLimitations.length)));
test('positive: both source conflicts retained with proxy',()=>{for(const d of input.definitions)assert.equal(d.protectedFacts.openConflicts.length,2);});
test('positive: all five loose cables are zero-solid endpoint schematics',()=>{const ds=input.definitions.filter(d=>d.recipe==='schematic');assert.equal(ds.length,5);assert(ds.every(d=>d.expectedRigidSolids===0&&d.protectedFacts.cable.endpointConnectorRefs.length));});
test('positive: four consumables are allocation abstractions',()=>{const ds=input.definitions.filter(d=>d.recipe==='abstract');assert.equal(ds.length,4);assert(ds.every(d=>d.expectedRigidSolids===0));});
test('positive: receipt complete without invented engineering admission',()=>{const d=input.definitions[0],shape={definitionId:d.definitionId,status:'PASS',solidCount:d.expectedRigidSolids,engineeringAdmission:false};assert(validateReceipt(receiptFor(d,shape,['x.svg']),input,shape,{checkArtifact:false}));});
test('positive: exact fifty once and six integral leads',()=>assert.deepEqual(validate(input),{status:'PASS',definitions:50,integralLeads:6,engineeringAdmission:false}));
for(const d of input.definitions)test('positive: actual receipt and independent shape '+d.definitionId,()=>{const r=read(path.join(base,'instructional-receipts',d.definitionId+'.json'));validateReceipt(r,input,r.validationResults.independentShape);});
