import fixtures from '../native/fixtures.json';
import type {Repository,Command,Backup} from '../../src/platform/repository';
import {canonical,hash} from '../../src/features/assembly-session/hash';
import {prepareCommand,emptySetup} from '../../src/features/assembly-session/commands';
import {captureLegacy} from '../../src/features/assembly-session/legacy';
export type Controls={fresh:()=>Promise<Repository>;restart:(r:Repository)=>Promise<Repository>;fault:(r:Repository,name:string)=>Promise<void>};
export async function runAdapterContract(control:Controls):Promise<Record<string,string>>{
 const f=fixtures as unknown as {setupCreate:Command;setupAppend:Command;stale:Command;reused:Command;journeys:Command[][];forged:Command;missing:Command;migration:Command;malformed:Command;fork:Command;reconcile:Command;setupBackup:Backup;sessionBackup:Backup};
 const result:Record<string,string>={};const pass=(name:string,ok:unknown)=>{if(!ok)throw Error('CONTRACT_FAILED:'+name);result[name]='PASS';};
 const reject=async(name:string,fn:()=>Promise<unknown>,code?:string)=>{try{await fn();throw Error('UNEXPECTED_ACCEPTANCE:'+name);}catch(e){if(String(e).includes('UNEXPECTED_ACCEPTANCE'))throw e;pass(name,!code||String(e).includes(code));}};
 let r=await control.fresh();const initial=await r.commit(f.setupCreate);pass('initial creation',initial.acknowledgedRevision===1);pass('lost acknowledgment exact retry',canonical(initial)===canonical(await r.commit(f.setupCreate)));await reject('changed command ID reuse',()=>r.commit(f.reused),'COMMAND_ID_REUSE');await r.commit(f.setupAppend);pass('append',(await r.load('PX-SETUP'))?.aggregate.revision===2);pass('duplicate before revision',canonical(initial)===canonical(await r.commit(f.setupCreate)));await reject('stale CAS',()=>r.commit(f.stale),'CONFLICT');r=await control.restart(r);pass('restart resume',(await r.load('PX-SETUP'))?.aggregate.revision===2);const backup=await r.backup();r.close();
 r=await control.fresh();await r.commit(f.setupCreate);const raced=await Promise.allSettled([r.commit(f.setupAppend),r.commit(f.stale)]);pass('two concurrent fresh writers',raced.filter(x=>x.status==='fulfilled').length===1&&raced.some(x=>x.status==='rejected'&&String(x.reason).includes('CONFLICT')));r.close();
 for(const fault of ['rollback','quota']){r=await control.fresh();await r.commit(f.setupCreate);await control.fault(r,fault);await reject(fault+' rejection',()=>r.commit(f.setupAppend));await control.fault(r,'clear');pass(fault+' atomicity',(await r.load('PX-SETUP'))?.aggregate.revision===1);const ack=await r.commit(f.setupAppend);pass(fault+' same-command retry',ack.acknowledgedRevision===2);r.close();}
 for(const fault of ['missingEvent','snapshot']){r=await control.fresh();await r.commit(f.setupCreate);await control.fault(r,fault);await reject(fault+' load rejection',()=>r.load('PX-SETUP'));await reject(fault+' append rejection',()=>r.commit(f.setupAppend));r.close();}
 for(const [index,journey]of f.journeys.entries()){r=await control.fresh();for(const c of journey){const ack=await r.commit(c);if(c.payload.kind==='complete')pass(`variant ${index} exact confirmation retry`,canonical(ack)===canonical(await r.commit(c)));}const s=(await r.load(journey[0].aggregateId))!.aggregate.snapshot as import('../../src/generated/twin/contracts').AssemblySession;pass(`variant ${index} all29 and invalidation`,s.confirmationRecords.length===29&&s.confirmationRecords.filter(c=>c.invalidatedByEventRef.state==='notApplicable').length===17);pass(`variant ${index} zeroing consumption and epochs`,s.zeroingAttestations.length===3&&s.zeroingAttestations.every(a=>a.consumedByCommandRef.state==='known'&&a.invalidationEventRef.state==='known')&&s.servoEpochs.every(e=>e.epoch===1));r.close();}
 r=await control.fresh();await r.commit(f.journeys[0][0]);await reject('forged observed snapshot',()=>r.commit(f.forged));r.close();r=await control.fresh();for(const c of f.journeys[0]){if(c.payload.kind==='condition')break;await r.commit(c);}await reject('missing procedure dependency',()=>r.commit(f.missing));r.close();
 const tamper=(c:Command,change:(c:Command)=>void)=>{const changed=structuredClone(c);change(changed);changed.nextHash=hash('aggregate',changed.proposal);const {requestHash:_,...body}=changed;changed.requestHash=hash('command',body);return changed;};
 r=await control.fresh();await reject('forged migration setup',()=>r.commit(tamper(f.migration,c=>{if(c.payload.kind==='legacy'&&c.payload.setup){c.payload.setup.pdfLastPage=99;c.proposal=c.payload.setup;}})));r.close();
 r=await control.fresh();await reject('unknown setup aggregate',()=>r.commit(tamper(f.setupCreate,c=>{c.aggregateId='TEST-UNKNOWN-AGGREGATE';})));r.close();
 for(const mutation of ['invalidation','retainedAttestations']){r=await control.fresh();for(const c of f.journeys[0].slice(0,-1))await r.commit(c);const bad=tamper(f.journeys[0].at(-1)!,c=>{const s=c.proposal as import('../../src/generated/twin/contracts').AssemblySession;if(mutation==='invalidation')s.confirmationRecords[28].invalidatedByEventRef={state:'notApplicable',reason:'No event recorded.'};else s.zeroingAttestations.pop();});await reject('incomplete '+mutation+' set',()=>r.commit(bad));pass(mutation+' rejection atomicity',(await r.load(bad.aggregateId))!.aggregate.revision===bad.expectedRevision);r.close();}
 r=await control.fresh();await control.fault(r,'rollback');await reject('migration interrupted before marker',()=>r.commit(f.migration));await control.fault(r,'clear');pass('migration rollback',(await r.imports()).length===0&&(await r.load('PX-SETUP'))===null);const migrated=await r.commit(f.migration);pass('migration interruption after marker',canonical(migrated)===canonical(await r.commit(f.migration)));const identityRetry={...f.migration,commandId:'TEST-MIGRATION-IDENTITY-RETRY'};const {requestHash:_,...body}=identityRetry;identityRetry.requestHash=hash('command',body);pass('migration identity retry',canonical(migrated)===canonical(await r.commit(identityRetry)));const raw=(await r.imports())[0].raw;pass('exact original retained',raw===f.migration.payload.kind.toString()||raw===(f.migration.payload as Extract<Command['payload'],{kind:'legacy'}>).record.raw);pass('legacy imports zero detailed confirmations',!('confirmationRecords' in (await r.load('PX-SETUP'))!.aggregate.snapshot));const divergent=captureLegacy('{"steps":{"parts":"done"}}','TEST-ORIGIN');await reject('legacy divergence no reimport',()=>r.commit(prepareCommand(null,{kind:'legacy',...divergent,choice:'initial'},'TEST-DIVERGENCE')),'CONFLICT');const old=(await r.load('PX-SETUP'))!.aggregate;await r.commit(prepareCommand(old,{kind:'legacy',...divergent,choice:'keepNew'},'TEST-KEEP-NEW'));pass('legacy keep new and both copies',(await r.imports()).length===2&&canonical((await r.load('PX-SETUP'))!.aggregate.snapshot)===canonical(old.snapshot));r.close();
 r=await control.fresh();await r.commit(f.malformed);pass('malformed quarantine raw retention',(await r.imports())[0].raw==='{bad'&&(await r.imports())[0].status==='quarantined');const oversized=captureLegacy('x'.repeat(8*1024*1024+1),'TEST-OVERSIZED');await r.quarantine(oversized.record);pass('oversized separate durable raw retention',(await r.imports()).some(i=>i.rawHash===oversized.record.rawHash&&i.raw===oversized.record.raw));r.close();
 r=await control.fresh();await r.restore(backup);pass('backup separate recovery',canonical((await r.load('PX-SETUP'))!.aggregate)===canonical(backup.aggregates[0].aggregate));await reject('recovery nonempty rejection',()=>r.restore(backup),'RECOVERY_DESTINATION_NOT_EMPTY');r.close();
 const mutations:Record<string,(b:Backup)=>void>={checksum:b=>{b.checksum='0'.repeat(64);},canonicalPath:b=>{(b as unknown as Record<string,unknown>).canonicalPath='../../digital-twin/assemblies/v40';},nestedPath:b=>{(b.aggregates[0].aggregate.snapshot as unknown as Record<string,unknown>).path='/owner/state';},missingEvent:b=>{b.aggregates[0].events.shift();},duplicateSequence:b=>{b.aggregates[0].events[1].sequence=1;},invalidSnapshot:b=>{(b.aggregates[0].aggregate.snapshot as import('../../src/platform/repository').Setup).pdfLastPage=99;},missingResult:b=>{b.results.pop();},unknownModel:b=>{b.aggregates[0].aggregate.modelHash='0'.repeat(64);},unknownGraph:b=>{b.aggregates[0].aggregate.graphHash='0'.repeat(64);}};
 for(const[name,mutate]of Object.entries(mutations)){r=await control.fresh();const b=structuredClone(backup);mutate(b);if(name!=='checksum'){const{checksum:_,...body}=b;b.checksum=hash('backup',body);}await reject('import '+name,()=>r.restore(b));pass('import '+name+' rollback',(await r.list()).length===0);r.close();}
 r=await control.fresh();for(const c of f.journeys[0].slice(0,-1))await r.commit(c);await r.commit(f.fork);const forked=(await r.load(f.fork.aggregateId))!.aggregate.snapshot as import('../../src/generated/twin/contracts').AssemblySession;pass('variant fork zero inherited confirmations',forked.confirmationRecords.length===0&&forked.procedureAcknowledgments.length===0&&forked.zeroingAttestations.length===0&&forked.servoEpochs.every(e=>e.epoch===0));await r.commit(f.reconcile);pass('explicit badge reconciliation',(await r.load('PX-SETUP'))!.aggregate.snapshot && ((await r.load('PX-SETUP'))!.aggregate.snapshot as import('../../src/platform/repository').Setup).steps.assembly==='done');const joint=await r.backup();r.close();r=await control.fresh();await r.restore(joint);pass('reconciliation import proof closure',(await r.list()).length===3);r.close();
 r=await control.fresh();for(const c of f.journeys[0])await r.commit(c);await reject('stale reconciliation rejects invalidated work',()=>r.commit(f.reconcile),'CONFLICT');r.close();
 r=await control.fresh();const retained=captureLegacy('x'.repeat(8*1024*1024+1),'TEST-EMPTY-RECOVERY');await r.quarantine(retained.record);await reject('recovery imports-only destination rejection',()=>r.restore(backup),'RECOVERY_DESTINATION_NOT_EMPTY');r.close();
 r=await control.fresh();await r.restore(f.sessionBackup);pass('complete session import replay',(await r.load(f.sessionBackup.aggregates[0].aggregate.id))?.aggregate.revision===f.sessionBackup.aggregates[0].aggregate.revision);r.close();
 r=await control.fresh();await r.commit(f.setupCreate);await control.fault(r,'newer');r=await control.restart(r);await reject('newer schema read only',()=>r.commit(f.setupAppend),'UNSUPPORTED_VERSION');pass('newer schema export',(await r.backup()).schemaVersion===2);r.close();return result;
}
