// M3-only read-only verification and receipts. Does not hash its own outputs or reports.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {execFileSync,spawnSync} from 'node:child_process';
import {inventory,sha,treeHash,verifyGeneration} from '../content-pipeline/publication';
import {verifySource} from '../content-pipeline/source';
import {procedurePreimage,type Context} from '../../src/features/assembly-session/commands';
import {hash} from '../../src/features/assembly-session/hash';
const app=process.cwd(),repo=path.resolve(app,'..'),out=path.join(repo,'docs/implementation/evidence/m3');
const read=(p:string)=>fs.readFileSync(path.join(repo,p));
const bind=(p:string)=>({path:p,rawSha256:sha(read(p)),bytes:read(p).length});
const json=(p:string)=>JSON.parse(read(p).toString());
const write=(name:string,value:unknown)=>fs.writeFileSync(path.join(out,name),JSON.stringify(value,null,2)+'\n');
const adoption=json('docs/implementation/evidence/m3/content-adoption.json');
for(const [name,key] of [['tools/content-pipeline/documentation-input-manifest.json','oldManifest'],['tools/content-pipeline/documentation-generation-baseline.json','oldBaseline'],['.content-publication/committed.json','oldGeneration']]){
 const raw=fs.readFileSync(path.join(adoption.priorRecoveryArchive,name));if(sha(raw)!==adoption[key].sha256||raw.length!==adoption[key].bytes)throw Error('ARCHIVE_RECEIPT_DRIFT');
}
for(const r of adoption.priorRoots)if(treeHash(path.join(adoption.priorRecoveryArchive,r.path))!==r.hash)throw Error('ARCHIVE_ROOT_DRIFT');
verifySource(app);verifyGeneration(app);
const receipt=json('picarx-companion/.content-publication/committed.json');
const privateCurrent=inventory(path.join(repo,'digital-twin/evidence/private'));
const privateGit=execFileSync('git',['ls-files','digital-twin/evidence/private'],{cwd:repo,encoding:'utf8'});if(privateGit)throw Error('TRACKED_PRIVATE_DATA');
const base=JSON.parse(execFileSync('git',['show','HEAD:picarx-companion/src-tauri/tauri.conf.json'],{cwd:repo,encoding:'utf8'}));
const current=json('picarx-companion/src-tauri/tauri.conf.json');
if(current.identifier!==base.identifier||JSON.stringify(current.app.windows)!==JSON.stringify(base.app.windows))throw Error('NATIVE_IDENTITY_DRIFT');
const cap='picarx-companion/src-tauri/capabilities/default.json';
if(!read(cap).equals(execFileSync('git',['show','HEAD:'+cap],{cwd:repo})))throw Error('DEFAULT_CAPABILITY_DRIFT');
const normal=json('picarx-companion/src-tauri/tauri.m3.json');
if(JSON.stringify(normal).match(/wdio|m3-test|m3_test/))throw Error('NORMAL_TEST_PRIVILEGE');
const target='/var/folders/_q/nsgwvvj51zlcw71s_yzz0s100000gn/T/picar-m3-native-compile-mRPDsKmn/target/debug/build';
const acl=fs.readdirSync(target).filter(d=>d.startsWith('picarx-companion-')).map(d=>path.join(target,d,'out/acl-manifests.json')).filter(p=>fs.existsSync(p)).map(p=>({path:p,raw:fs.readFileSync(p)}));
const normalAcl=acl.find(a=>a.raw.includes('commit_session_command')&&!a.raw.includes('wdio')&&!a.raw.includes('m3_test'));const defaultAcl=acl.find(a=>!a.raw.includes('commit_session_command')&&!a.raw.includes('wdio')&&!a.raw.includes('m3_test'));if(!normalAcl||!defaultAcl)throw Error('NORMAL_COMPILED_ACL_MISSING');
write('native-normal-capabilities.json',{status:'PASS',identifier:current.identifier,windowDefaults:current.app.windows,defaultCapability:bind(cap),normalConfig:bind('picarx-companion/src-tauri/tauri.m3.json'),csp:current.app.security.csp,normalCompiledAcl:{rawSha256:sha(normalAcl.raw),bytes:normalAcl.raw.length,testPrivileges:false},defaultCompiledAcl:{rawSha256:sha(defaultAcl.raw),bytes:defaultAcl.raw.length,testPrivileges:false},normalFeatureTree:bind('docs/implementation/evidence/m3/native-default-feature-tree.txt')});
const registry=json('digital-twin/validation/m2/runtime-registry.json');
const ledger=read('docs/digital-twin/V40_ASSEMBLY_LEDGER.md').toString();
const procedureText=Object.fromEntries(ledger.split(/(?=^## \d\d\.)/m).slice(1).map(t=>[t.match(/PX-V40-STEP-\d\d/)![0],t]));
const procedures=['rpi4','rpi5','rpi-zero-2-w'].flatMap(variant=>{const graph=json(`digital-twin/validation/m2/${variant}/compiled-graph.json`);const ctx={graph,registry,procedureText,evidenceHash:'e00e7825f413a37edeb3c9ac47611fbf790480d6efb71337b5cd219bfd082d5c'} as Context;return graph.operations.filter((o:any)=>['acknowledgeProcedure','confirmZeroing'].includes(o.kind)).map((o:any)=>{const preimage=procedurePreimage(ctx,o.id);return {variantId:variant,operationId:o.id,procedureRevisionHash:hash('procedure',preimage),preimage};});});
write('procedure-preimages.json',{sourceLedger:bind('docs/digital-twin/V40_ASSEMBLY_LEDGER.md'),procedures});
const browser=json('docs/implementation/evidence/m3/browser-parity-chromium.json'),webkit=json('docs/implementation/evidence/m3/browser-parity-webkit.json'),native=json('docs/implementation/evidence/m3/native-parity.json'),transfer=json('docs/implementation/evidence/m3/native-browser-transfer.json');
const sorted=(r:Record<string,string>)=>JSON.stringify(Object.entries(r).sort(([a],[b])=>a.localeCompare(b)));
if(Object.values(native.results).some(v=>v!=='PASS')||[browser.results,webkit.results,transfer.actualWebviewIndexedDB].some(r=>sorted(r)!==sorted(native.results)))throw Error('ADAPTER_PARITY_MISMATCH');
write('adapter-parity.json',{status:'PASS',scenarioCount:Object.keys(native.results).length,results:native.results,targets:[{adapter:'IndexedDB',engine:'Chromium',version:browser.version},{adapter:'IndexedDB',engine:'WebKit',version:webkit.version},{adapter:'SQLite',engine:'WDIO embedded WKWebView',version:'605.1.15'},{adapter:'IndexedDB',engine:'actual embedded WKWebView',version:'605.1.15'}],nativeGroups:6,nativeSessionTests:4,countsAreNotAdditive:true,transfer:{browserToDesktop:transfer.browserToDesktop,desktopToBrowser:transfer.desktopToBrowser,separateNativeRecovery:transfer.separateNativeRecovery}});
write('source-publication-closure.json',{status:'PASS',adoption:bind('docs/implementation/evidence/m3/content-adoption.json'),previousGenerationRecoverable:true,archiveVerified:true,currentGeneration:receipt,currentManifest:bind('picarx-companion/tools/content-pipeline/documentation-input-manifest.json'),currentBaseline:bind('picarx-companion/tools/content-pipeline/documentation-generation-baseline.json'),privateOriginalCount:privateCurrent.length,trackedPrivateCount:0,privateHashesPublished:false,sourceDelta:adoption.sourceDelta});
const commands=[['node',['digital-twin/tools/compiler/upstream.mjs','--check'],repo,'upstream-final-closure.txt'],['node',['digital-twin/tools/compiler/gate.mjs','--check'],repo,'graph-final-closure.txt'],['node',['digital-twin/tools/types.mjs','--check'],repo,'types-final-closure.txt'],['pnpm',['content:check'],app,'content-final-closure.txt'],['pnpm',['package:check'],app,'package-final-closure.txt']] as const;
const results=commands.map(([command,args,cwd,log])=>{const r=spawnSync(command,[...args],{cwd,encoding:'utf8',maxBuffer:16*1024*1024});fs.writeFileSync(path.join(out,log),r.stdout+'\n'+r.stderr);return {command:[command,...args],cwd,environment:{},exit:r.status,log:bind('docs/implementation/evidence/m3/'+log)};});write('closure-commands.json',results);if(results.some(r=>r.exit!==0))throw Error('CLOSURE_CHECK_FAILED');
const git=(args:string[])=>execFileSync('git',args,{cwd:repo,encoding:'utf8'}).trim();
write('closure-state.json',{branch:git(['branch','--show-current']),startHead:git(['rev-parse','HEAD']),status:git(['status','--short']),staged:git(['diff','--cached','--name-only']),diffCheck:git(['diff','--check']),privateTracked:privateGit,platform:os.platform(),architecture:os.arch(),node:process.version,pnpm:execFileSync('pnpm',['--version'],{encoding:'utf8'}).trim(),scope:'M3 only',m4Implemented:false});
console.log('M3 closure source/archive/capability/parity/upstream/content/package receipts PASS');
