// Ajv standalone generation keeps the exact closed schemas while avoiding runtime code compilation under CSP.
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import Ajv from 'ajv/dist/2020';
import addFormats from 'ajv-formats';
import standalone from 'ajv/dist/standalone';
const schemaRaw=fs.readFileSync('../digital-twin/schemas/digital-twin.schema.json'),searchRaw=fs.readFileSync('../digital-twin/schemas/m2-search-index.schema.json');
const schema=JSON.parse(schemaRaw.toString()),ajv=new Ajv({strict:false,code:{source:true,esm:true}});addFormats(ajv);ajv.addSchema(schema);ajv.addSchema({$id:'m3-session-validator',$ref:schema.$id+'#/$defs/AssemblySession'});ajv.addSchema(JSON.parse(searchRaw.toString()),'m3-search-validator');
let code=standalone(ajv,{validateSession:'m3-session-validator',validateSearch:'m3-search-validator'});
const replacements={'require("ajv/dist/runtime/ucs2length").default':'ucs2length','require("ajv-formats/dist/formats").fullFormats':'formatsModule.fullFormats','require("ajv/dist/runtime/equal").default':'equal'};
for(const [from,to]of Object.entries(replacements))code=code.replaceAll(from,to);if(code.includes('require('))throw Error('UNRECOGNIZED_STANDALONE_DEPENDENCY');
const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
code=`// Generated by tools/m3/generate-validators.ts; do not edit.\n// Schema bytes: ${sha(schemaRaw)}; search bytes: ${sha(searchRaw)}\nimport * as ucs2Module from 'ajv/dist/runtime/ucs2length.js';\nimport * as equalModule from 'ajv/dist/runtime/equal.js';\nimport * as formatsNamespace from 'ajv-formats/dist/formats.js';\nconst ucs2length=ucs2Module.default?.default??ucs2Module.default,equal=equalModule.default?.default??equalModule.default,formatsModule=formatsNamespace.fullFormats?formatsNamespace:formatsNamespace.default;\n`+code+'\n';
const path='src/platform/session-validators.js';if(process.argv.includes('--check')){if(fs.readFileSync(path,'utf8')!==code)throw Error('VALIDATOR_DRIFT');console.log('Standalone schema validators match exact schema bytes.');}else fs.writeFileSync(path,code);
