import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {test,expect, type Page} from '@playwright/test';
test.use({actionTimeout:10000});
const synthetic=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aJU0AAAAASUVORK5CYII=','base64');
const build=(p:Page)=>p.locator('.studio-build');
async function open(p:Page,n=0,v='rpi5'){await p.goto(`/#/studio/${v}/${n}?diagnostics`);await expect(p.locator('.studio')).toBeVisible();await expect(build(p)).not.toContainText('Opening saved');}
async function ledger(p:Page){return p.evaluate(async()=>{const {exportData}=await import(String('/src/features/assembly-session/store.ts')) as typeof import('../../src/features/assembly-session/store');return exportData();});}
test.beforeEach(async({page})=>{await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());});
test('owner session writes, separate variants, all nine physical steps, conservative undo, ordinary viewing is read only',async({page,browserName})=>{
 test.setTimeout(180000);await open(page);expect((await ledger(page)).aggregates).toHaveLength(0);await build(page).getByRole('button',{name:'Start build session'}).click();await expect(build(page)).toHaveAttribute('data-session','PX-STUDIO-RPI5');
 await page.locator('.studio-rail a').filter({hasText:/^2$/}).click();await expect(build(page)).not.toContainText('Saving /');await expect.poll(async()=>((await ledger(page)).aggregates[0]?.aggregate.snapshot as import('../../src/generated/twin/contracts').AssemblySession).reviewStepId).toBe('PX-V40-STEP-02');const before=await ledger(page);
 await page.getByRole('button',{name:'Play step',exact:true}).click();await page.waitForTimeout(500);await page.getByLabel('Step timeline').fill('1');await page.getByRole('button',{name:'Isolate',exact:true}).click();await page.getByRole('button',{name:'Ghost others',exact:true}).click();await page.getByRole('button',{name:'Explode',exact:true}).click();await page.getByRole('button',{name:'Deck clip',exact:true}).click();await page.keyboard.press('r');
 const canvas=page.locator('canvas').first(),box=(await canvas.boundingBox())!;await page.mouse.move(box.x+box.width*.45,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.55,{steps:5});await page.mouse.up();await page.mouse.click(box.x+box.width*.5,box.y+box.height*.55);expect(await ledger(page)).toEqual(before);
 await page.goto('/#/studio/rpi5');await expect(page.locator('.studio')).toHaveAttribute('data-step','2');
 for(let n=1;n<=9;n++){await open(page,n);for(const input of await build(page).locator('input[type=checkbox]').all())await input.check();await build(page).getByLabel('My physical completion statement').fill(`Synthetic owner confirmation for printed step ${n}.`);await build(page).getByRole('button',{name:'Mark physically done',exact:true}).click();await expect(build(page)).toContainText(`${n}/29 physically completed by owner`);await expect(build(page)).toContainText('does not clear M7');}
 await page.locator('.studio-boards a').filter({hasText:'Zero 2 W'}).click();await build(page).getByRole('button',{name:'Start build session'}).click();await expect(build(page)).toHaveAttribute('data-session','PX-STUDIO-ZERO2W');await expect(build(page)).toContainText('0/29');
 await page.locator('.studio-rail a').filter({hasText:/^3$/}).click();await expect.poll(async()=>((await ledger(page)).aggregates.find(a=>a.aggregate.id==='PX-STUDIO-ZERO2W')!.aggregate.snapshot as import('../../src/generated/twin/contracts').AssemblySession).reviewStepId).toBe('PX-V40-STEP-03');await expect(build(page)).not.toContainText('Saving /');const beforeSwitch=await ledger(page);
 await page.locator('.studio-boards a').filter({hasText:'Pi 5'}).click();await expect(page.locator('.studio')).toHaveAttribute('data-step','3');await expect(build(page)).toContainText('9/29');expect(await ledger(page)).toEqual(beforeSwitch);
 await page.locator('.studio-rail a').filter({hasText:/^Parts$/}).click();await page.locator('.studio-boards a').filter({hasText:'Zero 2 W'}).click();await expect(page.locator('.studio')).toHaveAttribute('data-step','0');await expect(build(page).getByRole('link',{name:'Return to saved Step 3'})).toBeVisible();expect(await ledger(page)).toEqual(beforeSwitch);
 await open(page,7);await build(page).getByRole('checkbox',{name:'Reopen this step and undo downstream physical confirmations.'}).check();await build(page).getByRole('button',{name:'Undo / reopen physical step'}).click();await expect(build(page)).toContainText('6/29');await page.reload();await expect(build(page)).toContainText('6/29');
 const saved=await ledger(page);expect(saved.aggregates.filter(a=>a.aggregate.graphHash)).toHaveLength(2);fs.writeFileSync(`../docs/implementation/evidence/studio-3/build-along-${browserName}.json`,JSON.stringify({browserName,sessionIds:saved.aggregates.map(a=>a.aggregate.id),events:saved.aggregates.map(a=>a.events.map(e=>e.action.kind)),readOnlyViewer:'PASS',physicalAndUndo:'PASS'},null,2)+'\n');
});
test('private synthetic photo copy/hash, failed copy, failed save and exact retry, selected ZIP and revision history',async({page:original,playwright,browserName})=>{
 const folder=browserName==='webkit'?fs.mkdtempSync(path.join(os.tmpdir(),'picar-studio-browser-')):null;
 const context=folder?await playwright.webkit.launchPersistentContext(folder,{headless:true,baseURL:'http://localhost:1420',viewport:{width:1440,height:900}}):null;
 const page=context?await context.newPage():original;
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());
 try{
 test.setTimeout(90000);await open(page,1);await build(page).getByRole('button',{name:'Start build session'}).click();await expect(build(page)).toHaveAttribute('data-session','PX-STUDIO-RPI5');const input=build(page).locator('input[type=file]');
 await input.setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('bad')});await expect(build(page).getByRole('alert')).toContainText('PHOTO_TYPE');expect((await ledger(page)).aggregates[0].events.filter(e=>e.action.kind==='observation')).toHaveLength(0);
 await page.evaluate(()=>{const add=IDBObjectStore.prototype.add;(window as any).restoreAdd=()=>IDBObjectStore.prototype.add=add;IDBObjectStore.prototype.add=function(...args){if(this.name==='events')throw new DOMException('TEST_QUOTA','QuotaExceededError');return add.apply(this,args);};});
 await input.setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:synthetic});const retry=build(page).getByRole('button',{name:'Retry pending save'});await expect(retry).toBeEnabled();await expect(build(page).getByRole('alert')).toContainText('TEST_QUOTA');expect((await ledger(page)).aggregates[0].events.filter(e=>e.action.kind==='observation')).toHaveLength(0);await page.evaluate(()=>(window as any).restoreAdd());await retry.click();await expect(build(page)).toContainText('1 photos');
 await input.setInputFiles({name:'unselected.png',mimeType:'image/png',buffer:synthetic});await expect(build(page)).toContainText('2 photos');await page.reload();await expect(build(page)).toContainText('2 photos');
 const results=await page.evaluate(async()=>{const {exportData}=await import(String('/src/features/assembly-session/store.ts')) as typeof import('../../src/features/assembly-session/store');const {readPhoto}=await import(String('/src/platform/evidence.ts')) as typeof import('../../src/platform/evidence');const {observationRevision}=await import(String('/src/features/assembly-session/observation.ts')) as typeof import('../../src/features/assembly-session/observation');const {evidenceZip}=await import(String('/src/features/assembly-session/evidence-zip.ts')) as typeof import('../../src/features/assembly-session/evidence-zip');const b=await exportData();const records=b.aggregates[0].events.filter(e=>e.action.kind==='observation').flatMap(e=>e.action.kind==='observation'?[e.action.record]:[]);const bytes=await readPhoto(records[0]);return {record:records[0],unselected:records[1].id,bytes:Array.from(bytes),earlier:observationRevision(records[0],'a'.repeat(64)),zip:Array.from(evidenceZip([{record:records[0],bytes}]))};});
 expect(Buffer.from(results.bytes)).toEqual(synthetic);expect(results.record.variantId).toBe('rpi5');expect(results.record.stepId).toBe('PX-V40-STEP-01');expect(results.earlier).toBe('Taken against an earlier digital revision');expect(Buffer.from(results.zip).toString()).not.toContain(results.unselected);
 await build(page).locator('details').evaluate(e=>(e as HTMLDetailsElement).open=true);await build(page).locator('details input[type=checkbox]').first().check();
 if(browserName==='chromium'){await page.evaluate(async()=>{const root=await navigator.storage.getDirectory();const handle=await root.getFileHandle('TEST-EXPORT-DESTINATION',{create:true});(window as any).showSaveFilePicker=async()=>handle;});await build(page).getByRole('button',{name:'Export selected private evidence ZIP'}).click();await expect(build(page)).toContainText('Evidence export saved');const chosen=await page.evaluate(async()=>{const root=await navigator.storage.getDirectory();const file=await (await root.getFileHandle('TEST-EXPORT-DESTINATION')).getFile();const bytes=Array.from(new Uint8Array(await file.arrayBuffer()));await root.removeEntry('TEST-EXPORT-DESTINATION');return bytes;});expect(Buffer.from(chosen)).toEqual(Buffer.from(results.zip));}
 // Explicitly exercise the browser download/Save As fallback as well as Chromium's destination-handle branch.
 await page.evaluate(()=>(window as any).showSaveFilePicker=undefined);const download=page.waitForEvent('download');await build(page).getByRole('button',{name:'Export selected private evidence ZIP'}).click();const d=await download;const destination=test.info().outputPath('selected-private-evidence.zip');await d.saveAs(destination);expect(fs.readFileSync(destination)).toEqual(Buffer.from(results.zip));
 fs.writeFileSync(`../docs/implementation/evidence/studio-3/observation-${browserName}.json`,JSON.stringify({browserName,syntheticOnly:true,copyAndHash:'PASS',failedCopy:'PASS',failedPersistenceThenSameRetry:'PASS',historicalRevision:'PASS',selectedZip:'PASS',exportDestination:'disposable Playwright output path',provenance:results.record},null,2)+'\n');
 }finally{await context?.close();if(folder)fs.rmSync(folder,{recursive:true,force:true});}
});
