import { useMemo, useState, useSyncExternalStore } from 'react';
import type { AssemblySession } from '../generated/twin/contracts';
import { useCompanion, createSession, loadSession, sessionAction, newId, saveError, reconcileAssembly, importData } from '../features/assembly-session/store';
import { acceptedContext, contexts } from '../features/assembly-session/accepted';
import { completed, condition, active } from '../features/assembly-session/commands';
import { assemblyStepHref, assemblyPartHref, navigate } from '../lib/router';
import { projectPrefix } from '../domain/assembly/reducer';
import { hash } from '../features/assembly-session/hash';
import { PdfViewer } from '../components/PdfViewer';
import sourceLock from '../../tools/content-pipeline/documentation-source-lock.json';
import '../styles/assembly.css';
const subscribe = () => () => {};
export default function Assembly({ sessionId, printedStep, partId }: { sessionId?: string; printedStep?: number; partId?: string }) {
 const state=useCompanion();const [variant,setVariant]=useState('rpi4');const [checked,setChecked]=useState<string[]>([]);const [statement,setStatement]=useState('');const [preview,setPreview]=useState<'before'|'after'>('before');const [busy,setBusy]=useState(false);const [undoAccepted,setUndoAccepted]=useState(false);
 const projection=useMemo(()=>{const s=state.selected && state.selected.id===sessionId?state.selected.snapshot as AssemblySession:null;const c=s?contexts.get(s.graphHash):undefined;if(!s||!c)return null;const n=printedStep??Number(s.reviewStepId.slice(-2));const prefix=c.graph.steps.slice(0,n-1+(preview==='after'?1:0)).reduce((sum,t)=>sum+t.operationIds.length,0);return projectPrefix(c,prefix,hash);},[state.selected,sessionId,printedStep,preview]);
 // The route subscribes to an idempotent loader. StrictMode repeats never create commands.
 useSyncExternalStore(()=>{if(sessionId)void loadSession(sessionId);return subscribe();},()=>sessionId??'overview');
 const session=state.selected && state.selected.id===sessionId?state.selected.snapshot as AssemblySession:null;
 const ctx=session?contexts.get(session.graphHash):undefined;
 const run=(f:()=>Promise<unknown>)=>{if(busy||state.pending)return;setBusy(true);void f().catch(saveError).finally(()=>setBusy(false));};
 if(!sessionId)return <main className="page doc"><h1>V40 Assembly</h1><p>29 source-backed steps. Reference-only guidance; geometry and physical observations are unavailable. Setup progress and physical self-confirmations are separate.</p>
 <label>Board variant <select value={variant} onChange={e=>setVariant(e.target.value)}><option value="rpi4">Raspberry Pi 4</option><option value="rpi5">Raspberry Pi 5</option><option value="rpi-zero-2-w">Raspberry Pi Zero 2 W</option></select></label>
 <button className="button primary" disabled={!state.initialized||busy||state.pending||!!state.error} onClick={()=>run(async()=>{const s=await createSession(variant);navigate(assemblyStepHref(s.id,s.variantId,1));})}>Start new session</button>
 <ul>{state.sessions.map(a=>{const s=a.snapshot as AssemblySession;return <li key={a.id}><a href={assemblyStepHref(s.id,s.variantId,Number(s.reviewStepId.slice(-2)))}>{s.variantId} · {completed(s).length}/29 self-confirmed · {s.id}</a></li>;})}</ul>
 <label>Import into a separate recovery store <input type="file" accept="application/json" disabled={state.pending||busy} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{if(file.size>8*1024*1024)throw Error('IMPORT_TOO_LARGE');await importData(await file.text());});}}/></label>
 <p>Imports are data only. Existing progress is never overwritten. Moving between browser origins and desktop requires an explicit export/import.</p></main>;
 if(!session||!ctx)return <main className="page"><h1>{state.error?'Session recovery':'Opening session…'}</h1><p role="alert">{state.error}</p><a href="#/assembly">Assembly overview</a></main>;
 const number=printedStep??Number(session.reviewStepId.slice(-2));const step=ctx.graph.steps.find(t=>t.printedNumber===number);
 if(!step)return <main className="page"><h1>Unknown printed step</h1><a href="#/assembly">Assembly overview</a></main>;
 const disabled=state.pending||busy;const done=completed(session);
 // The memoized projection is review state, never a physical ledger write.
 if(!projection)return <main className="page">Opening reference projection…</main>;
 const allIds=[...new Set([...step.introducedInstanceIds,...step.usedInstanceIds])];
 const item=(id:string)=>ctx.graph.instances.find(i=>i.id===id);const name=(id:string)=>ctx.registry.definitions.find(d=>d.id===item(id)?.definitionId)?.name??id;
 const target=partId?item(partId):null;
 if(partId&&!target)return <main className="page"><h1>Unknown part</h1><a href={assemblyStepHref(session.id,session.variantId,number)}>Return to step</a></main>;
 const conditions=ctx.graph.operations.filter(o=>step.operationIds.includes(o.id)&&['acknowledgeProcedure','confirmZeroing'].includes(o.kind));
 const panel=sourceLock.panels.find(p=>p.printedStep===number)?.mappings.find(p=>p.variants.includes(session.variantId));
 return <><aside className="ref-sidebar"><h2>Printed steps</h2><ol>{ctx.graph.steps.map(t=><li key={t.id}><a aria-current={t.id===step.id?'step':undefined} href={assemblyStepHref(session.id,session.variantId,t.printedNumber)}>{t.printedNumber}. {t.title} {done.includes(t.id)?'✓ self-confirmed':''}</a></li>)}</ol></aside>
 <main className="page doc" key={step.id}><p>{session.variantId} · {done.length}/29 self-confirmed · 0 observed · revision {session.revision}</p><h1 tabIndex={-1} ref={el=>{if(el&&!el.dataset.focused){el.dataset.focused="true";el.focus();}}}>{number}. {step.title}</h1>
 <p>Review and preview never confirm physical work or request power. Printed-plan stock is not observed owner inventory.</p>
 <div className="home-actions"><button className="button" onClick={()=>setPreview('before')}>Review before</button><button className="button" onClick={()=>setPreview('after')}>Preview after</button><a className="button" href={`#/reference/assemble?return=${encodeURIComponent(assemblyStepHref(session.id,session.variantId,number))}`}>Reference</a><a className="button" href={`#/videos/assemble?return=${encodeURIComponent(assemblyStepHref(session.id,session.variantId,number))}`}>Video · requires network</a></div>
 <p role="status">{preview==='before'?'Before':'After'} instruction projection: {projection.completedOperationIds.length} operations. Physical confirmations: {done.length}.</p>
 <section className="card"><h2>Source instructions</h2><pre className="source-text">{ctx.procedureText[step.id]}</pre><p>Owner photographs are withheld. Exact part shape, fit, torque, hidden engagement and electrical applicability remain unresolved.</p></section>
 <section><h2>{partId?name(partId):'Parts and hardware tray'}</h2><div className="source-tiles">{!partId&&allIds.length===0&&<p>No new tray parts in this source step. Geometry remains unavailable; use the accounted parts below.</p>}{(partId?[partId]:allIds).map(id=><article className="card" key={id}><h3><a href={assemblyPartHref(session.id,session.variantId,id,ctx.graph.initialState.instances.find(i=>i.instanceId===id)!.location,number)}>{name(id)}</a></h3><p>{id}</p><p>Source tile · geometry unavailable</p><p>Printed-plan disposition: {projection.instances.find(i=>i.instanceId===id)?.location}. Supply: {item(id)?.supplyOrigin}.</p></article>)}</div>
 <details><summary>All accounted parts, reserves and accessories</summary><ul>{ctx.graph.instances.map(i=><li className="card" key={i.id}><span>Source tile · geometry unavailable</span> <a href={assemblyPartHref(session.id,session.variantId,i.id,ctx.graph.initialState.instances.find(s=>s.instanceId===i.id)!.location,number)}>{name(i.id)}</a> · {ctx.graph.initialState.instances.find(s=>s.instanceId===i.id)?.location}</li>)}</ul></details></section>
 <section><h2>Tools and warnings</h2>{step.toolRequirementIds.map(id=><pre className="source-text" key={id}>{ctx.registry.tools.find(t=>t.id===id)?.purpose}</pre>)}{step.warningIds.map(id=><pre className="source-text" key={id}>{ctx.registry.warnings.find(w=>w.id===id)?.text}</pre>)}<p>Unresolved: {step.blockerIds.join(', ')}</p></section>
 <details><summary>Z0104V40 booklet · source page {panel?.pdfPage??'unavailable'}</summary><p>The locked PDF is verified by exact bytes. Source rectangles locate the printed panel and do not provide geometry.</p><PdfViewer src="/content/pdf/picar-x-assembly.pdf" requestedPage={panel?.pdfPage}/></details>
 <section className="card"><h2>Physical self-confirmation</h2><p>Confirm only work you have checked on your actual assembly. A checkbox records your statement and cannot certify engineering or electrical conflicts.</p>
 {conditions.map(op=>{const recorded=[...session.procedureAcknowledgments,...session.zeroingAttestations].some(r=>r.operationId===op.id&&active(r));return <div key={op.id}><p>{op.kind==='confirmZeroing'?'Scoped zeroing: deny movement since the printed zeroing procedure for this named servo.':'Acknowledge the exact printed power/procedure requirement above.'} {op.id}</p><button className="button" disabled={disabled||recorded||done.includes(step.id)} onClick={()=>run(()=>sessionAction({kind:'condition',record:condition(session,ctx,op.id,newId('CONDITION'),new Date().toISOString())},ctx))}>{recorded?'Recorded':'Record my acknowledgment'}</button></div>;})}
 {step.verificationRuleIds.map(id=><label className="assembly-check" key={id}><input type="checkbox" checked={checked.includes(id)} onChange={e=>setChecked(old=>e.target.checked?[...old,id]:old.filter(x=>x!==id))}/>{id} · checked against source instructions; unresolved engineering proof stays blocked</label>)}
 <label className="assembly-check">My statement <textarea value={statement} onChange={e=>setStatement(e.target.value)}/></label>
 <button className="button primary" disabled={disabled||done.includes(step.id)||!statement.trim()||!step.verificationRuleIds.every(id=>checked.includes(id))} onClick={()=>run(async()=>{await sessionAction({kind:'complete',stepId:step.id,statement,checkedRuleIds:step.verificationRuleIds,createdAt:new Date().toISOString()},ctx);setChecked([]);setStatement('');navigate(assemblyStepHref(session.id,session.variantId,Math.min(29,number+1)));})}>Confirm physical work and save</button>
 <label className="assembly-check"><input type="checkbox" checked={undoAccepted} onChange={e=>setUndoAccepted(e.target.checked)}/>I understand this invalidates this step and downstream physical self-confirmations.</label><button className="button" disabled={disabled||!undoAccepted} onClick={()=>run(()=>sessionAction({kind:'invalidate',stepId:step.id,servoInstanceId:null,reason:'undo',createdAt:new Date().toISOString()},ctx))}>Invalidate this step and downstream confirmations</button>
 {conditions.some(o=>o.kind==='confirmZeroing')&&<button className="button" disabled={disabled} onClick={()=>run(()=>sessionAction({kind:'invalidate',stepId:step.id,servoInstanceId:null,reason:'movement',createdAt:new Date().toISOString()},ctx))}>Report servo movement / replacement / horn reindexing</button>}
 </section><div className="home-actions"><a href={assemblyStepHref(session.id,session.variantId,Math.max(1,number-1))}>Previous review</a><a href={assemblyStepHref(session.id,session.variantId,Math.min(29,number+1))}>Next review</a><button className="button" disabled={disabled} onClick={()=>run(()=>sessionAction({kind:'bookmark',stepId:step.id},ctx))}>Save review bookmark</button></div>
 <label>Fork with zero inherited confirmations <select value={variant} onChange={e=>setVariant(e.target.value)}><option value="rpi4">Pi 4</option><option value="rpi5">Pi 5</option><option value="rpi-zero-2-w">Zero 2 W</option></select></label><button className="button" disabled={disabled} onClick={()=>run(async()=>{await acceptedContext(variant);const fork=await createSession(variant,session.id);navigate(assemblyStepHref(fork.id,fork.variantId,1));})}>Create separate variant session</button>
 {done.length===29&&<button className="button" disabled={disabled} onClick={()=>run(reconcileAssembly)}>Explicitly reconcile the setup assembly badge</button>}
 </main></>;
}
