import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {validateScope,coverage,evaluate,refuseEngineering,presentation,root} from './gate.mjs';
const read=p=>JSON.parse(fs.readFileSync(p));const scope=read(path.join(presentation,'product-scope.json'));
test('two active delivery boards preserve all three historical graphs',()=>validateScope(scope));
for(const [name,edit] of [['Pi4 active',s=>s.activeProductVariants.push('rpi4')],['Pico',s=>s.activeProductVariants.push('pico')],['generic Pi',s=>s.activeProductVariants=['raspberry-pi']],['87 product target',s=>s.requiredActiveStepVariantCoverage=87],['Pi4 blocked',s=>s.preservedNonTarget[0].status='BLOCKED'],['drop historical Pi4',s=>s.historicalSemanticVariants.shift()],['collapse FPC variants',s=>s.separateActiveVariantSemanticsRequired=false],['lose Q14',s=>s.zero2WAccessoryBlocker=null]])test('reject scope mutation '+name,()=>{const s=structuredClone(scope);edit(s);assert.throws(()=>validateScope(s));});
for(const purpose of ['G-CAD','G-GEOMETRY','engineeringMeasurement','engineeringInterface','engineeringSolver','engineeringRoute','manufacturing','physicalFit'])test('reject instructional engineering promotion '+purpose,()=>assert.throws(()=>refuseEngineering({track:'engineering',engineeringAdmission:true},purpose),/M7_ENGINEERING_PROOF_REQUIRED/));
const {rows}=coverage();const report={productScope:scope,rows,preservedNonTarget:[{variantId:'rpi4',status:'PRESERVED_NON_TARGET',historicalGraphHash:'ce9dd71eb9728f1538e2fb311f99450cdafc0df96c91033cf0333e6bec51eac7',newOutputsRequired:false}],engineeringAdmission:false,runtimeAdmission:false};
test('58 honest incomplete rows cannot become assembly acceptance',()=>assert.equal(evaluate(report),'BLOCKED'));
for(const [name,edit] of [['missing row',r=>r.rows.pop()],['duplicate row',r=>r.rows[1]=r.rows[0]],['Pi4 failed',r=>r.preservedNonTarget[0].status='FAIL'],['generator self PASS',r=>{r.rows[0].instructionalStatus='INSTRUCTIONAL_ADMITTED';r.rows[0].completeAssemblyOutput=true;r.rows[0].independentProofRef='forged';}],['engineering promotion',r=>r.rows[0].engineeringStatus='PASS']])test('reject report mutation '+name,()=>{const r=structuredClone(report);edit(r);assert.throws(()=>evaluate(r));});
test('S21 free joint, E-right/F-left, servo roles, wheels and temporary P11 preserved',()=>{
 for(const v of scope.activeProductVariants){const graph=read(path.join(root,'digital-twin/validation/m2',v,'compiled-graph.json'));
 const s21=graph.steps[20];const cs=graph.mechanicalConnections.filter(c=>s21.operationIds.includes(c.activationOperationId));assert(cs.some(c=>c.remainingDOF.length));
 const state=rows.find(r=>r.variantId===v&&r.printedNumber===29);assert(!state.activeCableConnectionIds.some(id=>id.includes('P11')));
 assert(graph.instances.some(i=>i.role.includes('pan'))&&graph.instances.some(i=>i.role.includes('tilt'))&&graph.instances.some(i=>i.role.includes('steering')));
 assert(graph.steps[25].usedInstanceIds.filter(id=>id.includes('WASHER-B')).length===6);
 assert(graph.steps[26].usedInstanceIds.some(id=>id.includes('WHEEL-REAR')));
 }
});
test('Zero2W accessory and Pi5 microphone remain separate',()=>{const allocations=read(path.join(root,'digital-twin/components/inventory/allocations.json')).filter(a=>a.instanceId==='PX-V40-INS-USB-MICROPHONE-001');assert.equal(allocations.find(a=>a.variantId==='rpi-zero-2-w').disposition,'accessory');assert.equal(allocations.find(a=>a.variantId==='rpi5').disposition,'plannedInstalled');assert(rows.find(r=>r.variantId==='rpi-zero-2-w'&&r.printedNumber===2).engineeringBlockerIds.includes('Q-14'));});

test('current coverage cannot repeat resolved chirality as an active blocker',()=>assert(rows.every(r=>!r.instructionalBlockers.includes('M7-PI5-BOARD-CHIRALITY'))));
test('revised board directions and separate Zero2W supports are retained',()=>{const pi=read(path.join(presentation,'pi5-board-direction-review-02.json'));assert.equal(pi.rootCause,'C. V40_SOURCE_INTERPRETATION_ERROR');assert.deepEqual(pi.requiredInstalledDirections.gpioSide,[0,-1,0]);const s=read(path.join(presentation,'step01-source-review-02.json'));for(const a of s.variantAllocations['rpi-zero-2-w']){const p=s.positions.find(p=>p.name===a.position);assert.equal(p.centerMm[1]>0,a.standoffInstanceId.includes('M25X11'));}});

test('revision03 anchor maps source-local flange up to installed down with explicit corner aliases',()=>{const s=read(path.join(presentation,'step01-source-review-03.json'));assert.deepEqual(s.plateAAnchor.rotation,[[1,0,0],[0,-1,0],[0,0,-1]]);assert.deepEqual(s.plateAAnchor.translationMm,[0,0,2]);for(const p of s.positions){assert.deepEqual(p.centerMm,[p.partLocalCenterMm[0],-p.partLocalCenterMm[1],0]);assert(p.partLocalName);}for(const a of s.variantAllocations['rpi-zero-2-w']){const p=s.positions.find(p=>p.name===a.position);assert.equal(p.centerMm[1]>0,a.standoffInstanceId.includes('M25X11'));}});
