import fs from 'node:fs';
import {newSession,prepareCommand,condition,eventFor,emptySetup} from '../../src/features/assembly-session/commands';
import type {Context} from '../../src/features/assembly-session/commands';
import type {Aggregate,Command,Backup} from '../../src/platform/repository';
import type {AssemblySession} from '../../src/generated/twin/contracts';
import {hash} from '../../src/features/assembly-session/hash';
import {captureLegacy} from '../../src/features/assembly-session/legacy';
const registry=JSON.parse(fs.readFileSync('../digital-twin/validation/m2/runtime-registry.json','utf8'));
const ledger=fs.readFileSync('../docs/digital-twin/V40_ASSEMBLY_LEDGER.md','utf8');
const procedureText=Object.fromEntries(ledger.split(/(?=^## \d\d\.)/m).slice(1).map(t=>[t.match(/PX-V40-STEP-\d\d/)![0],t]));
const contexts=['rpi4','rpi5','rpi-zero-2-w'].map(variant=>({graph:JSON.parse(fs.readFileSync(`../digital-twin/validation/m2/${variant}/compiled-graph.json`,'utf8')),registry,procedureText,evidenceHash:'e00e7825f413a37edeb3c9ac47611fbf790480d6efb71337b5cd219bfd082d5c'} as Context));
const ack=(c:Command)=>({aggregateId:c.aggregateId,commandId:c.commandId,acknowledgedRevision:c.expectedRevision+1,snapshotHash:c.nextHash});
const aggregate=(c:Command):Aggregate=>({id:c.aggregateId,revision:c.expectedRevision+1,graphHash:c.graphHash,modelHash:c.modelHash,snapshot:c.proposal,snapshotHash:c.nextHash});
const setupCreate=prepareCommand(null,{kind:'setup',setup:emptySetup()},'TEST-SETUP-CREATE');
const setupAppend=prepareCommand(aggregate(setupCreate),{kind:'setup',setup:{...emptySetup(),pdfLastPage:2}},'TEST-SETUP-APPEND');
const stale=prepareCommand(aggregate(setupCreate),{kind:'setup',setup:{...emptySetup(),pdfLastPage:3}},'TEST-STALE');
const reused=prepareCommand(null,{kind:'setup',setup:{...emptySetup(),pdfLastPage:3}},setupCreate.commandId);
const rehash=(c:Command)=>{c.nextHash=hash('aggregate',c.proposal);const{requestHash:_,...body}=c;c.requestHash=hash('command',body);return c;};
const journeys=contexts.map(ctx=>{const commands:Command[]=[];let old:Aggregate|null=null;let n=0;const commit=(action:Command['payload'])=>{const c=prepareCommand(old,action,`TEST-${ctx.graph.variantId.toUpperCase()}-${++n}`,ctx);old=aggregate(c);commands.push(c);};
commit({kind:'create',session:newSession('TEST-SESSION-'+ctx.graph.variantId.toUpperCase(),ctx),forkOf:null});
for(const step of ctx.graph.steps){for(const op of ctx.graph.operations.filter(o=>step.operationIds.includes(o.id)&&['acknowledgeProcedure','confirmZeroing'].includes(o.kind)))commit({kind:'condition',record:condition(old!.snapshot as AssemblySession,ctx,op.id,`TEST-CONDITION-${ctx.graph.variantId.toUpperCase()}-${++n}`,'2026-09-30T12:00:00Z')});commit({kind:'complete',stepId:step.id,statement:'I checked the printed physical task.',checkedRuleIds:step.verificationRuleIds,createdAt:'2026-09-30T12:00:00Z'});}
commit({kind:'invalidate',stepId:ctx.graph.steps[17].id,servoInstanceId:null,reason:'movement',createdAt:'2026-09-30T12:00:00Z'});return commands;});
const first=journeys[0][1];const forged=rehash({...structuredClone(first),commandId:'TEST-FORGED',proposal:{...first.proposal,observationIds:['TEST-OBSERVATION']}} as Command);
const missing=rehash({...structuredClone(journeys[0].find(c=>c.payload.kind==='condition')!),commandId:'TEST-MISSING-DEPENDENCY'});if(missing.payload.kind==='condition'){missing.payload.record.dependencyIds=['TEST-UNKNOWN'];const recordId=missing.payload.record.id;const a=missing.proposal as AssemblySession;const r=[...a.procedureAcknowledgments,...a.zeroingAttestations].find(r=>r.id===recordId)!;r.dependencyIds=['TEST-UNKNOWN'];}rehash(missing);
const legacy=captureLegacy(fs.readFileSync('tests/baseline/legacy.json','utf8'),'TEST-ORIGIN');const migration=prepareCommand(null,{kind:'legacy',...legacy,choice:'initial'},'TEST-MIGRATION');const malformed=prepareCommand(null,{kind:'legacy',...captureLegacy('{bad','TEST-ORIGIN'),choice:'initial'},'TEST-MALFORMED');
const backup=(commands:Command[]):Backup=>{const last=commands.at(-1)!;const body={format:'picar-sessions' as const,schemaVersion:1,aggregates:[{aggregate:aggregate(last),events:commands.map(eventFor)}],results:commands.map(c=>({commandId:c.commandId,requestHash:c.requestHash,acknowledgment:ack(c)})),imports:commands.flatMap(c=>c.payload.kind==='legacy'?[c.payload.record]:[])};return {...body,checksum:hash('backup',body)};};
const full=journeys[0].slice(0,-1),fullSession=aggregate(full.at(-1)!);
const fork=prepareCommand(null,{kind:'create',session:newSession('TEST-FORK-RPI5',contexts[1]),forkOf:fullSession.id},'TEST-FORK-CREATE',contexts[1]);
const reconcile=prepareCommand(null,{kind:'reconcile',sessionId:fullSession.id,sessionRevision:fullSession.revision,graphHash:fullSession.graphHash!},'TEST-RECONCILE');
fs.writeFileSync('tests/native/fixtures.json',JSON.stringify({setupCreate,setupAppend,stale,reused,journeys,forged,missing,migration,malformed,fork,reconcile,setupBackup:backup([setupCreate,setupAppend]),sessionBackup:backup(journeys[0])},null,2)+'\n');
